# In-plane irradiance

This notebook is a tutorial in how to calculate the solar irradiance in the plane of PV panel, also known as plane-of-array (POA) irradiance.

The notebook is hosted on Google Colab, which is an interactive computing environment that allows you to run Python Jupyter Notebooks in your browser without having to install Python.

Remember that to execute the code in a cell, click "Ctrl+Enter".

## Step 1: Install and load packages

The first step is to install and import some necessary Python packages.

Remember to execute the cells, simply click the cell and then Ctrl+Enter.

In [1]:
# Install pvlib on Google Colab, as this is not a standard package.
!pip install pvlib

In [1]:
import pvlib  # library for PV and solar calculations
import numpy as np  # library for math and linear algebra
import pandas as pd  # library for data analysis
import matplotlib.pyplot as plt  # library for plotting

## Step 1: Define location

The first step is to define the location where your system is placed.

👉 **Action**: Update the longitude for DTU Building 208 in the code below:

In [3]:
location = pvlib.location.Location(latitude=55.7874, longitude=)

## Step 2: Retrieve solar irradiance data

The next step is to retrieve solar irradiance data.

An easy way to do this is to use the [PVGIS service](https://re.jrc.ec.europa.eu/pvg_tools/en/).

The pvlib-python package has a convenient function to do this in Python, see [pvlib.iotools.get_pvgis_tmy](https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.iotools.get_pvgis_tmy.html).

Note, the retrieved dataset is a so-called Typical Meteorological Year (TMY), which has been created from historical data to represent a median year.

👉 **Action**: Plot the retrieved data. What parameters does the dataset contain?

In [4]:
data, meta = pvlib.iotools.get_pvgis_tmy(
    latitude=location.latitude,
    longitude=location.longitude,
)

# Write your code here

## Step 3: Inspect the metadata

In the code block above, the pvlib function ``get_pvgis_tmy`` returned two objects. The first object is called ``data`` and is a Pandas DataFrame with the time series data. The second object is called ``meta`` and is a dictionary containing metadata, i.e., information describing the dataset.

👉 **Action**: Inspect the ``meta`` object to determine which dataset the irradiance data comes from (*hint: look for the field radiation_db*). Is this a reanalysis or a satellite-derived dataset?

In [13]:
# Write your code here

## Step 3: Calculate solar position

Similar to the first exercise, you need to calculate the solar position. In this case, we are calculating the solar position for the time steps contained in the dataset.

In [31]:
solarposition = location.get_solarposition(data.index)

solarposition.head()

,apparent_zenith,zenith,apparent_elevation,elevation,azimuth,equation_of_time
time(UTC),,,,,,
1990-01-01 00:00:00+00:00,146.135170,146.135170,-56.135170,-56.135170,19.558696,-3.286217
1990-01-01 01:00:00+00:00,141.807049,141.807049,-51.807049,-51.807049,41.951970,-3.306034
1990-01-01 02:00:00+00:00,135.237126,135.237126,-45.237126,-45.237126,60.355670,-3.325842
1990-01-01 03:00:00+00:00,127.430710,127.430710,-37.430710,-37.430710,75.558628,-3.345641
1990-01-01 04:00:00+00:00,119.091995,119.091995,-29.091995,-29.091995,88.734329,-3.365431

## Step 4: Calculate in-plane irradiance

The irradiance data retrieved in Step 2 contain the standard components: global horizontal irradiance (GHI), diffuse horizontal irradiance (DHI), and direct normal irradiance (DNI).

If we were to put our PV panel completely horizontal, we could simply use GHI as the incident irradiance on the panel. However, tilting PV panels can increase the incident irradiance. We therefore need to estimate the irradiance on a tilted plane using a so-called "transposition" model. Again, pvlib-python contains a convenient function for doing this, called [``get_total_irradiance``](https://pvlib-python.readthedocs.io/en/stable/reference/generated/pvlib.irradiance.get_total_irradiance.html).

The code cell below calculates the solar irradiance incident on a tilted plane.

👉 **Action**: Update the values for the albedo and surface tilt, and azimuth based on your design.
👉 **Action**: Plot the monthly irradiance.

In [23]:
# Update the surface tilt and azimuth values
surface_tilt = 
surface_azimuth = 
albedo = 

poa_irradiance = pvlib.irradiance.get_total_irradiance(
    surface_tilt=surface_tilt,
    surface_azimuth=surface_azimuth,
    solar_zenith=solarposition['apparent_zenith'],
    solar_azimuth=solarposition['azimuth'],
    dni=data['dni'],
    ghi=data['ghi'],
    dhi=data['dhi'],
    albedo=albedo,
    model='haydavies',
    dni_extra=pvlib.irradiance.get_extra_radiation(data.index),
)

poa_irradiance.head()

# Write your code below this line

,poa_global,poa_direct,poa_diffuse,poa_sky_diffuse,poa_ground_diffuse
time(UTC),,,,,
1990-01-01 00:00:00+00:00,0.0,0.0,0.0,0.0,0.0
1990-01-01 01:00:00+00:00,0.0,0.0,0.0,0.0,0.0
1990-01-01 02:00:00+00:00,0.0,0.0,0.0,0.0,0.0
1990-01-01 03:00:00+00:00,0.0,0.0,0.0,0.0,0.0
1990-01-01 04:00:00+00:00,0.0,0.0,0.0,0.0,0.0

The DataFrame ``poa_irradiance`` contains several columns with the prefix ``poa_``. The column ``poa_global`` is the total irradiance incident on the titled surface. ``poa_global`` is the sum of ``poa_direct`` and ``poa_diffuse``.

## Step 5: Find the optimal orientation

The main consideration for how to orient the PV panels on the buoy should be to optimize the PV power production.

👉 **Action**: Determine which orientation gives the highest energy yield (``poa_global``).

In [21]:
# Write your code here